# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageSizeDialog.ui',
# licensing of 'ImageSizeDialog.ui' applies.
#
# Created: Tue Feb 26 17:28:00 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ImageSizeDialog(object):
    def setupUi(self, ImageSizeDialog):
        ImageSizeDialog.setObjectName("ImageSizeDialog")
        ImageSizeDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ImageSizeDialog.resize(510, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImageSizeDialog.sizePolicy().hasHeightForWidth())
        ImageSizeDialog.setSizePolicy(sizePolicy)
        ImageSizeDialog.setMinimumSize(QtCore.QSize(510, 200))
        ImageSizeDialog.setMaximumSize(QtCore.QSize(510, 200))
        self.formLayout = QtWidgets.QFormLayout(ImageSizeDialog)
        self.formLayout.setObjectName("formLayout")
        self.originalSizeLabel = QtWidgets.QLabel(ImageSizeDialog)
        self.originalSizeLabel.setText("")
        self.originalSizeLabel.setObjectName("originalSizeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originalSizeLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ImageSizeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widthSpinBox = QtWidgets.QSpinBox(ImageSizeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthSpinBox.sizePolicy().hasHeightForWidth())
        self.widthSpinBox.setSizePolicy(sizePolicy)
        self.widthSpinBox.setMinimum(1)
        self.widthSpinBox.setMaximum(16777215)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.horizontalLayout.addWidget(self.widthSpinBox)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.lockAspect = QtWidgets.QRadioButton(ImageSizeDialog)
        self.lockAspect.setText("")
        self.lockAspect.setIconSize(QtCore.QSize(20, 20))
        self.lockAspect.setChecked(True)
        self.lockAspect.setObjectName("lockAspect")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lockAspect)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ImageSizeDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.heightSpinBox = QtWidgets.QSpinBox(ImageSizeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightSpinBox.sizePolicy().hasHeightForWidth())
        self.heightSpinBox.setSizePolicy(sizePolicy)
        self.heightSpinBox.setMinimum(1)
        self.heightSpinBox.setMaximum(16777215)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.horizontalLayout_2.addWidget(self.heightSpinBox)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImageSizeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Discard)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_3 = QtWidgets.QLabel(ImageSizeDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_3)

        self.retranslateUi(ImageSizeDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ImageSizeDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ImageSizeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ImageSizeDialog)

    def retranslateUi(self, ImageSizeDialog):
        ImageSizeDialog.setWindowTitle(QtWidgets.QApplication.translate("ImageSizeDialog", "Image Size", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ImageSizeDialog", "Width ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ImageSizeDialog", "Height", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ImageSizeDialog", "Lock", None, -1))

